apiVersion: v1
kind: Secret
metadata:
  name: project-secrets
type: Opaque
stringData:
  # W tym miejscu na produkcji podajemy prawdziwe hasła i klucze
  # Nigdy nie komitujemy tego pliku z jawnymi kluczami (można to zarządzać przez np. SealedSecrets / sops)
  
  # BOT
  DISCORD_TOKEN: "your-discord-token-here"
  STEAM_API_KEY: "your-steam-api-key-here"
  BOT_DB_PASS: "bot_super_secret"
  
  # FRONTEND
  NEXTAUTH_SECRET: "your-nextauth-secret-here"
  FRONT_DB_PASS: "front_super_secret"
